### ISSUE TITLE
Sync configuration b/w client and server

### ISSUE THREAD

**Issue by misaugstad** [payros/super-gomoku#2]
We want to have the option to change the board dimensions, timeout, etc. on the front-end. This info isn't being saved on the back-end right now, which is causing invalid moves played by bots if we change the board dimensions.

@payros has these config parameters saved in the session variables, which are sent to along with any post/get request. So I just need to save those on the back-end now.

**Comment by misaugstad** [comment]
@payros did you have some example you were working off of, or documentation? I'm having trouble finding anything that matches what you did on the front-end.

**Comment by misaugstad** [comment]
@payros did you have some example you were working off of, or documentation? I'm having trouble finding anything that matches what you did on the front-end.

**Comment by payros** [comment]
It shouldn't really match what I did in the front-end, since you're not writing to localStorage, just reading. To figure out how to get the session variable, I would start with the [documentation on Yesod about Client Sessions](https://www.yesodweb.com/book/sessions#sessions_clientsession). On that same page, you will also find a [good example](https://www.yesodweb.com/book/sessions#sessions_session_operations) on how to get the session from inside the handler and retrieve the value using a key. It should be pretty straightforward.

**Comment by payros** [comment]
I think the handler should look something like this:

```
postSyncSettingsR :: Handler String
postSyncSettingsR = do
    rawSettings <- lookupSession "settings"  
    let settings = unpackSettings rawSettings -- 'rawSettings' will be a JSON object represented as a string
    dim = Dim (dimN settings) (dimM settings) (dimK settings) -- This is probably wrong, since dim is a global variable and I'm not sure you can change it inside a function
    timeout = settings.timeout 
```


Consider this pseudo code since I'm sure I'm butchering Haskell types and such, but that's the general idea. After you save `dim`and `timeout`the bot's will be able to use them. You're also gonna have to unpack them on getHomeR and update `dim`, `boardRows`, `boardCols` and `timeout`. Come to think of it, you can probably make that a separate function called `updateSettings` and call that from the handler.

**Comment by misaugstad** [comment]
Right, so I had done this, when I show the results from `getSession`, I get `fromList []`, it is empty :(

**Comment by misaugstad** [comment]
And looking up "settings" gets me a `Nothing` b/c the session is an empty list of key-value pairs

**Comment by payros** [comment]
They should be empty by default unless the user resets the board. Did you save new settings on the browser (for your local deployment)?

**Comment by payros** [comment]
After reading the documentation more closely, it seems Yesod stores its own encrypted key/value pairs as cookies, and ignores everything else. 

With that in mind, we may have to modify our strategy to either use Yesod client storage as the default (and make calls to the backend to get and update them) or use localStorage as the default and make calls to the backend to update the global variables when they are modified. I vote for the second one, since most of the code is already in place.

I can modify `syncSettings` to include the latest params to be updated on the backend.

**Comment by misaugstad** [comment]
>With that in mind, we may have to modify our strategy to either use Yesod client storage as the default (and make calls to the backend to get and update them) or use localStorage as the default and make calls to the backend to update the global variables when they are modified. I vote for the second one, since most of the code is already in place.

Sounds good to me!

**Comment by payros** [comment]
Just committed the code with modified `/syncSettings` request that includes the `settings` param you need.

I also added a dummy `postSyncSettingsR` handler to Server.hs, but feel free to do whatever you want with it.

**Comment by misaugstad** [comment]
Okay, the thing is... There aren't just variable that can be updated in Haskell :) Why don't we just send the dimensions, tiles to win, and timeout along with nextMove request?

**Comment by misaugstad** [comment]
The code to implement this was merged in [this commit](https://github.com/payros/super-gomoku/commit/72b8948f1ab7bd045ecdc0d0d17d2ed7034d59e8).
